branches:
  only:
    - master
    - customers_management
language: python
python:
  - "3.3"
  - "3.4"

install:
  - pip install -r requirements.txt

script:
  - nosetests
  - behave user_service/tests/integration/users_crud.feature
