"""empty message

Revision ID: 16701869471
Revises: None
Create Date: 2014-12-15 23:13:53.975770

"""

# revision identifiers, used by Alembic.
revision = '16701869471'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('version', sa.DateTime, nullable=True),
    sa.Column('creation_date', sa.DateTime, nullable=True),
    sa.Column('updated_by', sa.String(120), nullable=True),
    sa.Column('id', sa.String(255), nullable=False),
    sa.Column('first_name', sa.String(50), nullable=False),
    sa.Column('last_name', sa.String(50), nullable=False),
    sa.Column('phone', sa.String(14), nullable=False),
    sa.Column('birth_date', sa.Date, nullable=False),
    sa.Column('email', sa.String(50), nullable=True),
    sa.Column('password', sa.String(20), nullable=False),
    sa.Column('active', sa.Boolean, autoincrement=False, nullable=True),
    sa.Column('admin', sa.Boolean, autoincrement=False, nullable=True),
    sa.Column('last_login_at', sa.DateTime, nullable=True),
    sa.Column('current_login_at', sa.DateTime, nullable=True),
    sa.Column('last_login_ip', sa.String(16), nullable=True),
    sa.Column('current_login_ip', sa.String(16), nullable=True),
    sa.Column('confirmed_at', sa.DateTime, nullable=True),
    sa.Column('login_count', sa.Integer, autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.Integer, autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('roles',
    sa.Column('version', sa.DateTime, nullable=True),
    sa.Column('creation_date', sa.DateTime, nullable=True),
    sa.Column('updated_by', sa.String(120), nullable=True),
    sa.Column('id', sa.String(255), nullable=False),
    sa.Column('name', sa.String(80), nullable=True),
    sa.Column('description', sa.String(200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('roles_users',
    sa.Column('user_id', sa.String(255), nullable=True),
    sa.Column('role_id', sa.String(255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='roles_users_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='roles_users_ibfk_1'),
    )

    op.create_table('countries',
    sa.Column('version', sa.DateTime, nullable=True),
    sa.Column('creation_date', sa.DateTime, nullable=True),
    sa.Column('updated_by', sa.String(120), nullable=True),
    sa.Column('id', sa.Integer, nullable=False),
    sa.Column('code', sa.String(3), nullable=False),
    sa.Column('name', sa.String(100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )

    op.create_table('regions',
    sa.Column('version', sa.DateTime, nullable=True),
    sa.Column('creation_date', sa.DateTime, nullable=True),
    sa.Column('updated_by', sa.String(120), nullable=True),
    sa.Column('id', sa.Integer, nullable=False),
    sa.Column('code', sa.String(3), nullable=False),
    sa.Column('name', sa.String(100), nullable=False),
    sa.Column('country_id', sa.Integer, autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='regions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    )

    op.create_table('cities',
    sa.Column('version', sa.DateTime, nullable=True),
    sa.Column('creation_date', sa.DateTime, nullable=True),
    sa.Column('updated_by', sa.String(120), nullable=True),
    sa.Column('id', sa.Integer, nullable=False),
    sa.Column('name', sa.String(100), nullable=False),
    sa.Column('region_id', sa.Integer, autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='cities_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    )

    op.create_table('customers',
    sa.Column('version', sa.DateTime, nullable=True),
    sa.Column('creation_date', sa.DateTime, nullable=True),
    sa.Column('updated_by', sa.String(120), nullable=True),
    sa.Column('id', sa.String(255), nullable=False),
    sa.Column('name', sa.String(100), nullable=False),
    sa.Column('type', sa.String(2), nullable=False),
    sa.Column('unique_id', sa.String(30), nullable=False),
    sa.Column('phone', sa.String(14), nullable=False),
    sa.Column('address', sa.String(255), nullable=False),
    sa.Column('iban', sa.String(50), nullable=True),
    sa.Column('bank', sa.String(100), nullable=True),
    sa.Column('swift', sa.String(20), nullable=True),
    sa.Column('city_id', sa.Integer, autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name='customers_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    )

    op.create_table('addresses',
    sa.Column('version', sa.DateTime, nullable=True),
    sa.Column('creation_date', sa.DateTime, nullable=True),
    sa.Column('updated_by', sa.String(120), nullable=True),
    sa.Column('id', sa.String(255), nullable=False),
    sa.Column('contact_person', sa.String(255), nullable=False),
    sa.Column('phone', sa.String(14), nullable=False),
    sa.Column('address', sa.String(255), nullable=False),
    sa.Column('is_default', sa.Boolean, nullable=False, default=False),
    sa.Column('customer_id', sa.Integer, nullable=False),
    sa.Column('city_id', sa.Integer, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name='addresses_ibfk_1'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='addresses_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    )

    ### end Alembic commands ###



def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    op.drop_table('countries')
    op.drop_table('customers')
    op.drop_table('regions')
    op.drop_table('roles')
    op.drop_table('roles_users')
    op.drop_table('users')
    ### end Alembic commands ###
